#!/usr/bin/env bash

help_text="\
Usage: $0 DOMAIN [PATH]

Extract URLs from all links (<a> tags) found in html retrieved from
DOMAIN[/PATH]. Skips any URL that does not begin with http[s].
"

arg1=$1
arg2=$2

#
# fail <msg>
#
# print error message & exit
#
# msg:    a message to print
function fail {
    printf "$1\n" >&2
    printf "$0 failed with args:\n" >&2
    printf "    \$1: $arg1\n" >&2
    printf "    \$2: $arg2\n" >&2
    printf "see output above for more information\n" >&2
    exit 1
}

domain=`expr 'www.google.com/test/two' : '\([^/]*\)'`       # get domain from arg0 by tail of
                          # string beginning with first `/`
path=$arg2
target="$domain/$path"    # build target url

printf "fetching html from $target with 'curl'"
html=`curl $target`
resn=$?

if [ $resn -ne 0 ]; then
    fail "fetching html from $target with 'curl' failed ($resn)"
fi

printf "successfully fetched!\n"
printf "$html"
